
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';



export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const RESET_UPDATE_PASSWORD_REQUEST = 'RESET_UPDATE_PASSWORD_REQUEST';
export const RESET_UPDATE_PASSWORD_SUCCESS = 'RESET_UPDATE_PASSWORD_SUCCESS';
export const RESET_UPDATE_PASSWORD_ERROR = 'RESET_UPDATE_PASSWORD_ERROR';

export const REQUEST_GET_ALL_TASKS = 'REQUEST_GET_ALL_TASKS';
export const SUCCESS_GET_ALL_TASKS = 'SUCCESS_GET_ALL_TASKS';
export const ERROR_GET_ALL_TASKS = 'ERROR_GET_ALL_TASKS';


export const REQUEST_ADD_TASKS = 'REQUEST_ADD_TASKS';
export const SUCCESS_ADD_TASKS = 'SUCCESS_ADD_TASKS';
export const ERROR_ADD_TASKS = 'ERROR_ADD_TASKS';